apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-app-alerts
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  groups:
  - name: main.rules
    rules:
    - alert: HostHighCpuLoad
      expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 50
      for: 2m
      labels:
        severity: warning
        namespace: monitoring
      annotations:
        summary: "High CPU load detected on {{ $labels.instance }}"
        description: "CPU load is above 50% for more than 10 minutes.\nInstance: {{ $labels.instance }}\nCurrent value: {{ $value }}%"
        runbook_url: "https://example.com/runbooks/high-cpu-load"
    
    - alert: KubernetesPodCrashLooping
      expr: kube_pod_container_status_restarts_total > 5
      for: 0m
      labels:
        severity: critical
        namespace: monitoring
      annotations:
        summary: "Pod is in CrashLoopBackOff state"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 5 times in the last 5 minutes. restarte {{ $value }} times.\nPlease investigate the pod logs for more details."
        runbook_url: "https://example.com/runbooks/pod-crash-looping"